{% set name = "dash-leaflet" %}
{% set version = "1.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_leaflet-{{ version }}.tar.gz
  sha256: 79a3e19b0be9a5cf23873a0cd73153de224cbd756ddb30e2ffcee9ba23875e40

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dash
    - geobuf
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - dash_leaflet
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/thedirtyfew/dash-leaflet
  summary: Leaflet component for Dash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mitchellwood
